version: "3.9"
services:
  gtd-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: gtd-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Safety net: ensure timezone is set even if .env forgets it
      - TZ=Europe/Athens
    # No volumes required; the bot talks to Nextcloud via WebDAV.
    # If you want logs on the host, uncomment:
    # volumes:
    #   - ./logs:/var/log/gtd
    healthcheck:
      # "Is the process running?" simple liveness probe
      test: ["CMD-SHELL", "pgrep -f gtd_bot.py >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

